name: Build

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup node
      uses: actions/setup-node@v4

    - run: npm i
    - run: npm run build
