name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    # Runs a set of commands using the runners shell
    - name: setup node
      uses: actions/setup-node@v1  

    - run: npm i
    - run: npm run build
    - run: npm run export

    # - name: Setup SSH
    #   uses: kielabokkie/ssh-key-and-known-hosts-action@v1
    #   with:
    #     ssh-private-key: ${{ secrets.KEY }}
    #     ssh-host: ${{ secrets.HOST }}
    #     ssh-port: ${{ secrets.PORT }}
    
    # - name: ls -la via ssh
    #   uses: fifsky/ssh-action@master
    #   with:
    #     command: |
    #       pwd
    #       ls -la
    #     host: ${{ secrets.HOST }}
    #     user: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     port: ${{ secrets.PORT }}
    #     args: -tt

    - name: ls -la via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.PASSWORD }}
        script: ls -la

  # - name: Deploy to Staging server
  #   uses: easingthemes/ssh-deploy@v2.1.5
  #   env:
  #     SSH_PRIVATE_KEY: ${{ secrets.KEY }}
  #     ARGS: "-rltgoDzvO"
  #     SOURCE: "out/"
  #     REMOTE_HOST: ${{ secrets.HOST }}
  #     REMOTE_PORT: ${{ secrets.PORT }}
  #     REMOTE_USER: ${{ secrets.USERNAME }}
  #     TARGET: /home/grudinin/www/work
