name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup node
      uses: actions/setup-node@v4

    - run: npm i
    - run: npm run build

    - name: Delete old stuff
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: rm -rf www/work/*; exit;

    - name: Copy new stuff
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "out/"
        target: "www/work/"
        strip_components: 1
