name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup node
      uses: actions/setup-node@v4

    - run: npm i
    - run: npm run build

    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.IP }}
          ssh_private_key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          local_path: 'out/*'
          remote_path: 'www/work/'
          sftpArgs: '-o ConnectTimeout=5'
          delete_remote_files: true
