name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup node
      uses: actions/setup-node@v4

    # - name: Configure SSH
    #   run: |
    #     mkdir -p ~/.ssh/
    #     ls -l
    #     echo "$SSH_KEY" > ~/.ssh/prod.key
    #     chmod 600 ~/.ssh/prod.key
    #     cat >>~/.ssh/config <<END
    #     Host prod
    #       HostName $SSH_HOST
    #       User $SSH_USER
    #       Port $SSH_PORT
    #       IdentityFile ~/.ssh/prod.key
    #       StrictHostKeyChecking no
    #       PreferredAuthentications publickey
    #     END
    #   env:
    #     SSH_USER: ${{ secrets.USERNAME }}
    #     SSH_KEY: ${{ secrets.KEY }}
    #     SSH_HOST: ${{ secrets.HOST }}
    #     SSH_PORT: ${{ secrets.PORT }}

    # - name: Install SSH Key
    #   uses: shimataro/ssh-key-action@v2
    #   with:
    #     key: ${{ secrets.KEY }}
    #     known_hosts: 'a'

    # - run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      
    - run: npm i
    - run: npm run build
    # - run: ssh prod 'ls -l'
    # - run: ssh prod 'rm -rf www/work/*; exit;'

    # - name: Deploy with rsync
    #   run: rsync -avz out/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:www/work/
  
    - name: Copy new stuff
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.HOST }}
        remote-user: ${{ secrets.USERNAME }}
        private-ssh-key: ${{ secrets.KEY }}
        ssh-port: ${{ secrets.PORT }}
        source-path: "out/"
        destination-path: "www/work/"
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     port: ${{ secrets.PORT }}
    #     source: "out/"
    #     target: "www/work/"
    #     debug: true
    #     strip_components: 1
